version: "3.8"
services:
  # add front here
  api:
    container_name: api
    restart: always
    image: zohabanam/docker-test-app:latest
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URI: mongodb://mongo:27017/base
    networks:
      - app-net

  redis:
    container_name: redis
    image: redis:5
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - app-net
  mongo:
    container_name: mongo
    image: mongo:4.2
    restart: always
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
    volumes:
      - mongo-data:/data/db
    command: mongod --smallfiles --logpath=/dev/null
    networks:
      - app-net
volumes:
  mongo-data:
  redis-data:
networks:
  app-net:
