version: "3.8"
services:
  # add front here
  api:
    container_name: api
    restart: always
    image: zohabanam/docker-test-app:latest
    ports:
      - "3005:3005"
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - mongo
      - redis
    environment:
      PORT: 3005
      MONGODB_URI: mongodb://mongo:27017/base
      REDIS_HOST: redis
      NODE_ENV: production
    networks:
      - api

  redis:
    container_name: redis
    image: redis:5
    restart: always
    volumes:
      - redis:/data
    networks:
      - api
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: always
    volumes:
      - mongo:/data/db
    networks:
      - api
volumes:
  mongo:
  redis:
networks:
  api:
